
class GNeo4jEdges:
    SHARES_ENTITY = "SHARES_ENTITY"
    SHARES_CONCEPT = "SHARES_CONCEPT"
    SHARES_KEYWORD = "SHARES_KEYWORD"
    SHARES_PHRASE = "SHARES_PHRASE"
    SHARES_ACRONYM = "SHARES_ACRONYM"
