
class GNeo4jEdges:
    SHARES_ENTITY = "SHARES_ENTITY"
    SHARES_CONCEPT = "SHARES_CONCEPT"
    SHARES_KEYWORD = "SHARES_KEYWORD"
    SHARES_PHRASE = "SHARES_PHRASE"
    SHARES_ACRONYM = "SHARES_ACRONYM"


class GN4jNodes:
    CHUNK = "CHUNK"
    ORGANIZATION = "ORGANIZATION"
    PROJECT = "PROJECT"


class GN4jNodesIds:
    CHUNK_ID = "id"
    ORGANIZATION_ID = "id"
    PROJECT_ID = "id"
