"""ocr_audio_video_metadata_added

Revision ID: 0a473b346d39
Revises: b55ce0f27d5e
Create Date: 2026-07-26 15:56:46.014005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a473b346d39'
down_revision: Union[str, Sequence[str], None] = 'b55ce0f27d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_models', sa.Column('model_metadata', sa.JSON(), nullable=True))
    op.add_column('ocr_models', sa.Column('model_metadata', sa.JSON(), nullable=True))
    op.add_column('video_models', sa.Column('model_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_models', 'model_metadata')
    op.drop_column('ocr_models', 'model_metadata')
    op.drop_column('audio_models', 'model_metadata')
    # ### end Alembic commands ###
