"""project_config_init_and_update_project

Revision ID: 110b1d084803
Revises: 127b86a4180d
Create Date: 2026-08-03 23:51:17.303396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110b1d084803'
down_revision: Union[str, Sequence[str], None] = '127b86a4180d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('graph_db_enable', sa.Boolean(), nullable=False),
    sa.Column('reranker_enable', sa.Boolean(), nullable=False),
    sa.Column('sparse_embedding_enable', sa.Boolean(), nullable=False),
    sa.Column('llm_tag_extraction_enable', sa.Boolean(), nullable=False),
    sa.Column('llm_model_id', sa.Uuid(), nullable=False),
    sa.Column('llm_model_credential_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_model_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_model_credential_id', sa.Uuid(), nullable=False),
    sa.Column('ocr_model_id', sa.Uuid(), nullable=True),
    sa.Column('ocr_model_credential_id', sa.Uuid(), nullable=True),
    sa.Column('sparse_text_model_id', sa.Uuid(), nullable=True),
    sa.Column('sparse_text_model_credential_id', sa.Uuid(), nullable=True),
    sa.Column('reranker_model_id', sa.Uuid(), nullable=True),
    sa.Column('reranker_model_credential_id', sa.Uuid(), nullable=True),
    sa.Column('audio_model_id', sa.Uuid(), nullable=True),
    sa.Column('audio_model_credential_id', sa.Uuid(), nullable=True),
    sa.Column('video_model_id', sa.Uuid(), nullable=True),
    sa.Column('video_model_credential_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['audio_model_id'], ['audio_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['embedding_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['llm_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ocr_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ocr_model_id'], ['ocr_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reranker_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reranker_model_id'], ['reranker_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sparse_text_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sparse_text_model_id'], ['sparse_text_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_model_id'], ['video_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_configs_project_id'), 'project_configs', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('project_metadata', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('projects_llm_model_credential_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_llm_model_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_sparse_text_model_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_reranker_model_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_embedding_model_credential_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_embedding_model_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'embedding_model_credential_id')
    op.drop_column('projects', 'llm_model_id')
    op.drop_column('projects', 'llm_model_credential_id')
    op.drop_column('projects', 'embedding_model_id')
    op.drop_column('projects', 'reranker_model_id')
    op.drop_column('projects', 'sparse_text_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sparse_text_model_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('reranker_model_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('embedding_model_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('llm_model_credential_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('llm_model_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('embedding_model_credential_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projects_embedding_model_id_fkey'), 'projects', 'embedding_models', ['embedding_model_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('projects_embedding_model_credential_id_fkey'), 'projects', 'model_credentials', ['embedding_model_credential_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('projects_reranker_model_id_fkey'), 'projects', 'reranker_models', ['reranker_model_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('projects_sparse_text_model_id_fkey'), 'projects', 'sparse_text_models', ['sparse_text_model_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('projects_llm_model_id_fkey'), 'projects', 'llm_models', ['llm_model_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('projects_llm_model_credential_id_fkey'), 'projects', 'model_credentials', ['llm_model_credential_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('projects', 'project_metadata')
    op.drop_index(op.f('ix_project_configs_project_id'), table_name='project_configs')
    op.drop_table('project_configs')
    # ### end Alembic commands ###
