"""webhook_init

Revision ID: 127b86a4180d
Revises: 8dfa89a1d31b
Create Date: 2026-08-01 17:41:17.028289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127b86a4180d'
down_revision: Union[str, Sequence[str], None] = '8dfa89a1d31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_org_id'), 'webhooks', ['org_id'], unique=False)
    op.create_index(op.f('ix_webhooks_project_id'), 'webhooks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_project_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_org_id'), table_name='webhooks')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
