"""size_in_document

Revision ID: 2603c54e08e8
Revises: 0f85cfaf0f05
Create Date: 2026-05-24 17:02:30.583206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2603c54e08e8'
down_revision: Union[str, Sequence[str], None] = '0f85cfaf0f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'size')
    # ### end Alembic commands ###
