"""added_gte_edge_vector_similar_top_k

Revision ID: 65a656fbe407
Revises: 8329b69119a8
Create Date: 2026-08-18 22:45:03.526298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a656fbe407'
down_revision: Union[str, Sequence[str], None] = '8329b69119a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_variables', sa.Column('gte_edge_vector_similar_top_k', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_variables', 'gte_edge_vector_similar_top_k')
    # ### end Alembic commands ###
