"""document_ocr_needed_colomn_added

Revision ID: 6a6b682a3a8d
Revises: 110b1d084803
Create Date: 2026-08-08 22:21:21.852098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6b682a3a8d'
down_revision: Union[str, Sequence[str], None] = '110b1d084803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_ocr_needed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_ocr_needed')
    # ### end Alembic commands ###
