"""org_id_index

Revision ID: 74b2e9477c08
Revises: b5a6f5a5d04a
Create Date: 2026-05-03 10:59:55.150229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b2e9477c08'
down_revision: Union[str, Sequence[str], None] = 'b5a6f5a5d04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding_models', 'org_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_embedding_models_org_id'), 'embedding_models', ['org_id'], unique=False)
    op.create_foreign_key(None, 'embedding_models', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('llm_models', 'org_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_llm_models_org_id'), 'llm_models', ['org_id'], unique=False)
    op.create_foreign_key(None, 'llm_models', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('model_credentials', 'org_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_model_credentials_org_id'), 'model_credentials', ['org_id'], unique=False)
    op.create_foreign_key(None, 'model_credentials', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reranker_models', 'org_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_reranker_models_org_id'), 'reranker_models', ['org_id'], unique=False)
    op.create_foreign_key(None, 'reranker_models', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sparse_text_models', 'org_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_sparse_text_models_org_id'), 'sparse_text_models', ['org_id'], unique=False)
    op.create_foreign_key(None, 'sparse_text_models', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sparse_text_models', type_='foreignkey')
    op.drop_index(op.f('ix_sparse_text_models_org_id'), table_name='sparse_text_models')
    op.alter_column('sparse_text_models', 'org_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'reranker_models', type_='foreignkey')
    op.drop_index(op.f('ix_reranker_models_org_id'), table_name='reranker_models')
    op.alter_column('reranker_models', 'org_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'model_credentials', type_='foreignkey')
    op.drop_index(op.f('ix_model_credentials_org_id'), table_name='model_credentials')
    op.alter_column('model_credentials', 'org_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'llm_models', type_='foreignkey')
    op.drop_index(op.f('ix_llm_models_org_id'), table_name='llm_models')
    op.alter_column('llm_models', 'org_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'embedding_models', type_='foreignkey')
    op.drop_index(op.f('ix_embedding_models_org_id'), table_name='embedding_models')
    op.alter_column('embedding_models', 'org_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
