"""sparse_mode_update

Revision ID: 8dfa89a1d31b
Revises: f2ba27e0e31d
Create Date: 2026-08-01 15:27:37.575418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfa89a1d31b'
down_revision: Union[str, Sequence[str], None] = 'f2ba27e0e31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sparse_text_models', sa.Column('provider_type', sa.String(length=255), nullable=False))
    op.add_column('sparse_text_models', sa.Column('model_name', sa.String(length=255), nullable=False))
    op.add_column('sparse_text_models', sa.Column('model_id', sa.String(length=255), nullable=False))
    op.add_column('sparse_text_models', sa.Column('model_metadata', sa.JSON(), nullable=True))
    op.alter_column('sparse_text_models', 'size_in_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('sparse_text_models', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sparse_text_models', sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('sparse_text_models', 'size_in_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('sparse_text_models', 'model_metadata')
    op.drop_column('sparse_text_models', 'model_id')
    op.drop_column('sparse_text_models', 'model_name')
    op.drop_column('sparse_text_models', 'provider_type')
    # ### end Alembic commands ###
