"""added_next_start_page_l1_init

Revision ID: a0035214a5a1
Revises: fc8d9260a9ab
Create Date: 2026-08-20 00:04:34.544713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0035214a5a1'
down_revision: Union[str, Sequence[str], None] = 'fc8d9260a9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_processing_states', sa.Column('next_start_page', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_processing_states', 'next_start_page')
    # ### end Alembic commands ###
