"""project_variables_init

Revision ID: a1964bd7bedd
Revises: 6a6b682a3a8d
Create Date: 2026-08-18 18:42:04.128921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1964bd7bedd'
down_revision: Union[str, Sequence[str], None] = '6a6b682a3a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_variables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_chunk_batch_size', sa.Integer(), nullable=False),
    sa.Column('sparse_chunk_batch_size', sa.Integer(), nullable=False),
    sa.Column('llm_tag_extraction_batch_size', sa.Integer(), nullable=False),
    sa.Column('delay_between_chunk_processing_seconds', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('max_chunks', sa.Integer(), nullable=False),
    sa.Column('max_chunk_size_mb', sa.Float(), nullable=False),
    sa.Column('max_pages_per_batch', sa.Integer(), nullable=False),
    sa.Column('tail_carry_chars', sa.Integer(), nullable=False),
    sa.Column('group_size_for_rag_chunk', sa.Integer(), nullable=False),
    sa.Column('max_group_size_for_rag_chunk', sa.Integer(), nullable=False),
    sa.Column('objects_per_buffer', sa.Integer(), nullable=False),
    sa.Column('rows_per_io_buffer', sa.Integer(), nullable=False),
    sa.Column('video_segment_duration_minutes', sa.Float(), nullable=False),
    sa.Column('video_overlap_minutes', sa.Float(), nullable=False),
    sa.Column('video_max_duration_per_rag_chunk', sa.Float(), nullable=False),
    sa.Column('video_max_words_per_rag_chunk', sa.Integer(), nullable=False),
    sa.Column('audio_segment_duration_minutes', sa.Float(), nullable=False),
    sa.Column('audio_overlap_minutes', sa.Float(), nullable=False),
    sa.Column('audio_max_duration_per_rag_chunk', sa.Float(), nullable=False),
    sa.Column('audio_max_words_per_rag_chunk', sa.Integer(), nullable=False),
    sa.Column('gte_edge_vector_similar_threshold', sa.Float(), nullable=False),
    sa.Column('gte_qdrant_point_score_threshold', sa.Float(), nullable=False),
    sa.Column('eq_max_lane_count', sa.Integer(), nullable=False),
    sa.Column('eq_max_lane_entity', sa.Integer(), nullable=False),
    sa.Column('eq_gte_lane_weight_threshold', sa.Float(), nullable=False),
    sa.Column('eq_max_lane_chunks', sa.Integer(), nullable=False),
    sa.Column('eq_max_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_variables_project_id'), 'project_variables', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_variables_project_id'), table_name='project_variables')
    op.drop_table('project_variables')
    # ### end Alembic commands ###
