"""project

Revision ID: b5a6f5a5d04a
Revises: c659d1caad0d
Create Date: 2026-05-03 10:40:49.593230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a6f5a5d04a'
down_revision: Union[str, Sequence[str], None] = 'c659d1caad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('readable_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('llm_model_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_model_id', sa.Uuid(), nullable=False),
    sa.Column('sparse_text_model_id', sa.Uuid(), nullable=False),
    sa.Column('reranker_model_id', sa.Uuid(), nullable=False),
    sa.Column('llm_model_credential_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_model_credential_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['llm_model_credential_id'], ['model_credentials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reranker_model_id'], ['reranker_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sparse_text_model_id'], ['sparse_text_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index(op.f('ix_projects_readable_id'), 'projects', ['readable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_readable_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
