"""l1_checkpointing_init

Revision ID: fc8d9260a9ab
Revises: 65a656fbe407
Create Date: 2026-08-19 22:58:07.087561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8d9260a9ab'
down_revision: Union[str, Sequence[str], None] = '65a656fbe407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('last_file_chunk_number', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('next_rag_start_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_start_row', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_start_object', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_start_unit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_processing_states_document_id'), 'document_processing_states', ['document_id'], unique=True)
    op.create_index(op.f('ix_document_processing_states_org_id'), 'document_processing_states', ['org_id'], unique=False)
    op.create_index(op.f('ix_document_processing_states_project_id'), 'document_processing_states', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_states_project_id'), table_name='document_processing_states')
    op.drop_index(op.f('ix_document_processing_states_org_id'), table_name='document_processing_states')
    op.drop_index(op.f('ix_document_processing_states_document_id'), table_name='document_processing_states')
    op.drop_table('document_processing_states')
    # ### end Alembic commands ###
